const items = [
    {
        id: '101',
        image: 'wireless_earbuds.jpg',
        company: 'SoundBlaze',
        item_name: 'True Wireless Earbuds Pro 2',
        original_price: 5999,
        current_price: 2799,
        discount_percentage: 53,
        return_period: 10,
        delivery_date: '22 Apr 2025',
        rating: {
            stars: 4.4,
            count: 920,
        },
    },
    {
        id: '102',
        image: 'mechanical_keyboard.jpg',
        company: 'KeyNest',
        item_name: 'RGB Mechanical Gaming Keyboard',
        original_price: 4999,
        current_price: 3299,
        discount_percentage: 34,
        return_period: 7,
        delivery_date: '23 Apr 2025',
        rating: {
            stars: 4.6,
            count: 580,
        },
    },
    {
        id: '103',
        image: 'fitness_band.jpg',
        company: 'FitGo',
        item_name: 'Smart Fitness Band with Heart Rate Monitor',
        original_price: 2999,
        current_price: 1349,
        discount_percentage: 55,
        return_period: 14,
        delivery_date: '21 Apr 2025',
        rating: {
            stars: 4.1,
            count: 1100,
        },
    },
    {
        id: '104',
        image: 'bluetooth_speaker.jpg',
        company: 'BeatBox',
        item_name: 'Portable Bluetooth Speaker',
        original_price: 1999,
        current_price: 999,
        discount_percentage: 50,
        return_period: 15,
        delivery_date: '22 Apr 2025',
        rating: {
            stars: 4.3,
            count: 430,
        },
    },
    {
        id: '105',
        image: 'laptop_stand.jpg',
        company: 'ErgoPro',
        item_name: 'Aluminum Adjustable Laptop Stand',
        original_price: 1599,
        current_price: 799,
        discount_percentage: 50,
        return_period: 10,
        delivery_date: '24 Apr 2025',
        rating: {
            stars: 4.5,
            count: 620,
        },
    },
    {
        id: '106',
        image: 'smartwatch.jpg',
        company: 'WristTech',
        item_name: 'Smartwatch with AMOLED Display',
        original_price: 8999,
        current_price: 5799,
        discount_percentage: 36,
        return_period: 14,
        delivery_date: '20 Apr 2025',
        rating: {
            stars: 4.7,
            count: 1340,
        },
    },
    {
        id: '107',
        image: 'usb_hub.jpg',
        company: 'PlugMate',
        item_name: '5-in-1 USB-C Hub Adapter',
        original_price: 2499,
        current_price: 1199,
        discount_percentage: 52,
        return_period: 7,
        delivery_date: '22 Apr 2025',
        rating: {
            stars: 4.2,
            count: 270,
        },
    },
    {
        id: '108',
        image: 'laptop_cleaning_kit.jpg',
        company: 'CleanX',
        item_name: 'Complete Laptop Cleaning Kit',
        original_price: 899,
        current_price: 449,
        discount_percentage: 50,
        return_period: 5,
        delivery_date: '23 Apr 2025',
        rating: {
            stars: 4.0,
            count: 95,
        },
    }
];
